disabled_rules:
   - force_cast
   - identifier_name
   - opening_brace
   - large_tuple
   - type_name
   - unowned_variable_capture
   - line_length
   - multiple_closures_with_trailing_closure
   - multiline_arguments
   - trailing_comma
excluded:
  - "**/R.generated.swift"
  - R.generated.swift
  - Packages
  - .build
  - build
  - .idea
  - .swiftpm
  - "**/Package.swift"
  - "**/SnapshotHelper.swift"
  - fastlane
  - cleema-kit
  - ReSurge
opt_in_rules:
  - empty_string
  - last_where
  - flatmap_over_map_reduce
  - anyobject_protocol
  - closure_spacing
  - literal_expression_end_indentation
  - multiline_arguments
  - unowned_variable_capture
  - unneeded_parentheses_in_closure_argument
nesting:
    type_level: 2
identifier_name:
  excluded:
    - ID
    - id
    - x
    - y
    - z
custom_rules:
 # force_https: # From https://github.com/Twigz/Game
 #   name: "Force HTTPS over HTTP"
 #   regex: '((?i)http(?!s))'
 #   match_kinds: string
 #   message: "HTTPS should be favored over HTTP"
 #   severity: warning
  double_space: # From https://github.com/IBM-Swift/Package-Builder
    include: "*.swift"
    name: "Double space"
    regex: '([a-z,A-Z] \s+)'
    message: "Double space between keywords"
    match_kinds: keyword
    severity: warning
  auto_generated_leftovers:
    regex: 'func [^\n]*\{\n(\s*super\.[^\n]*\n(\s*\/\/[^\n]*\n)*|(\s*\/\/[^\n]*\n)+)\s*\}'
    message: "Delete auto-generated functions that you don't use"
  comments_space: # From https://github.com/brandenr/swiftlintconfig
    name: "Space After Comment"
    regex: '(^ *//\w+)'
    message: "There should be a space after //"
    severity: warning
  short_timeout:
    include: "*Tests.swift"
    name: "Short timeout"
    message: "Please do not use too short timeouts"
    regex: "defaultTimeout ="
    severity: error

